version: '3.9'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=cinemadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
#    command: --init-file /data/application/init.sql
    volumes:
      - ./data/db:/var/lib/postgresql/data
#      - ./init.sql:/var/lib/postgresql/data/docker-entrypoint-initdb.d/1-init.sql
