# Generated by Django 4.0.3 on 2022-03-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id_cinema', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cinemas/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id_hall', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('count_places', models.IntegerField()),
                ('count_rows', models.IntegerField()),
                ('count_columns', models.IntegerField()),
                ('id_cinema', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id_seat', models.AutoField(primary_key=True, serialize=False)),
                ('number_place', models.IntegerField()),
                ('number_row', models.IntegerField()),
                ('id_hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.hall')),
                ('id_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.sector')),
            ],
        ),
    ]
