# Generated by Django 4.0.3 on 2022-03-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleRental',
            fields=[
                ('id_rental', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_rental', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_session', models.DateTimeField()),
                ('id_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.hall')),
                ('id_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie')),
            ],
        ),
    ]
