# Generated by Django 3.2 on 2022-03-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='id_hall',
            new_name='hall',
        ),
        migrations.RenameField(
            model_name='moviesession',
            old_name='id_movie',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='schedulerental',
            old_name='id_movie',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='id_hall',
            new_name='hall',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='id_sector',
            new_name='sector',
        ),
    ]
