# Generated by Django 3.2 on 2022-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20220324_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='count_places',
            field=models.IntegerField(default=10),
        ),
    ]
