# Generated by Django 3.2 on 2022-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_hall_count_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='count_places',
            field=models.IntegerField(),
        ),
    ]
