# Generated by Django 3.2 on 2022-03-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_birth_date'),
        ('cinema', '0003_hall_count_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('datetime_book', models.DateTimeField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seat', to='cinema.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ms', to='cinema.moviesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user')),
            ],
            options={
                'unique_together': {('session', 'seat')},
            },
        ),
    ]
