# Generated by Django 3.2 on 2022-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='number_row',
            field=models.IntegerField(default=0),
        ),
    ]
