# Generated by Django 3.2 on 2022-05-22 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_booking_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_ticket',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
