# Generated by Django 3.2 on 2022-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_cinema_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='count_columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hall',
            name='count_rows',
            field=models.IntegerField(default=0),
        ),
    ]
