# Generated by Django 4.0.3 on 2022-03-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='movie_countries', to='movie.country')),
                ('genres', models.ManyToManyField(blank=True, related_name='movie_genres', to='movie.genre')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id_studio', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovieComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie')),
                ('id_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.personaldata')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='movie_studios', to='movie.studio'),
        ),
        migrations.CreateModel(
            name='MovieStudios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.studio')),
            ],
            options={
                'unique_together': {('movie', 'studio')},
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='m_genre', to='movie.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_genre', to='movie.movie')),
            ],
            options={
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='MovieCountries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.country')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie')),
            ],
            options={
                'unique_together': {('movie', 'country')},
            },
        ),
    ]
